---
version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["bundle", "exec", "bin/rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - db
    entrypoint: ["/app/bin/wait_for", "db:3306", "--"]
    environment:
      DB_HOST: db
      DB_PASSWORD: livSbI9IIoawmhk5
      RACK_ENV: development
    ports:
      - 3000:3000/tcp
    tmpfs: /app/tmp
    volumes:
      - ./:/app/:rw
      - node_modules:/app/node_modules
  runner:
    build:
      context: ./
      dockerfile: Dockerfile
    command: rspec
    depends_on:
      - db
    entrypoint: ["/app/bin/wait_for", "db:3306", "--"]
    environment:
      DATABASE_URL: mysql2://root:livSbI9IIoawmhk5@db/eagsmaster_test
      RACK_ENV: test
    volumes:
      - ./:/app/:rw
  db:
    environment:
      MYSQL_ROOT_PASSWORD: livSbI9IIoawmhk5
    image: mysql:5.7
volumes:
  node_modules:
