#!/usr/bin/env bash

version=$1

if [[ "$1" == '' ]]
  then
    echo "Please supply a version number"
    echo "Example:"
    echo "dev/release 1.2.3"
    exit 1
fi

project_id="$(gcloud config get-value project -q)"

docker build -t "eagsmaster:$version" . \
  && docker tag "eagsmaster:$version" "gcr.io/$project_id/eagsmaster:$version" \
  && docker push "gcr.io/$project_id/eagsmaster:$version" \
  && helm upgrade eagsmaster ./k8s/eagsmaster --set "image.tag=$version" \
  && git tag "$version"
