#!/usr/bin/env bash

version=$1

if [[ "$1" == '' ]]
  then
    echo "Please supply a version number"
    echo "Example:"
    echo "dev/release 1.2.3"
    exit 1
fi

project_id="$(gcloud config get-value project -q)"

docker login \
  && docker buildx build --platform linux/arm64,linux/amd64 --push -t "jimbali/eagsmaster:$version" . \
  && kubectx raspberry-pi \
  && helm upgrade eagsmaster ./k8s/eagsmaster --set "image.tag=$version" \
  && git tag "$version"
