version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker compose run -d ci tail -f /dev/null
     - run: docker compose exec ci bundle exec rails db:create db:migrate
     - run: docker compose exec ci bundle exec rspec
     - run: docker compose down -v
