version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker-compose run runner bundle exec rails db:create db:migrate
     - run: docker-compose run runner bundle exec rspec
