apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: eagsmaster-ingress
spec:
  rules:
  - host: eagsmaster.jimba.li
    http:
      paths:
      - backend:
          serviceName: eagsmaster
          servicePort: 3000
        path: /
  tls:
  - hosts:
    - eagsmaster.jimba.li
    secretName: eagsmaster-tls
