apiVersion: v1
kind: Service
metadata:
  name: {{ include "eagsmaster.fullname" . }}
  labels:
    {{- include "eagsmaster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    {{- include "eagsmaster.selectorLabels" . | nindent 4 }}
